import { analyzeFile, expectToBeDefined, expectTrackType, fixturePath } from './utils'

it('should parse file', async () => {
  const result = await analyzeFile(fixturePath('file_example_MP4_480_1_5MG.mp4'))
  expectToBeDefined(result.media)

  const { track } = result.media
  expect(track).toHaveLength(3)
  const [track0, track1, track2] = track

  expectTrackType(track0, 'General')
  expect(track0.Format).toBe('MPEG-4')
  expect(track0.Format_Profile).toBe('Base Media / Version 2')
  expect(track0.CodecID).toBe('mp42')
  expect(track0.CodecID_Compatible).toBe('mp42/mp41/isom/avc1')
  expect(track0.FileSize).toBe('1570024')
  expect(track0.Duration).toBeCloseTo(30.527)
  expect(track0.OverallBitRate).toBeNear(411_445, 2)
  expect(track0.FrameRate).toBeCloseTo(30)
  expect(track0.FrameCount).toBe(901)
  expect(track0.StreamSize).toBe(11_872)
  expect(track0.HeaderSize).toBe(11_864)
  expect(track0.DataSize).toBe(1_558_160)
  expect(track0.FooterSize).toBe(0)
  expect(track0.IsStreamable).toBe('Yes')

  expectTrackType(track1, 'Video')
  expect(track1.StreamOrder).toBe('0')
  expect(track1.ID).toBe('1')
  expect(track1.Format).toBe('AVC')
  expect(track1.Format_Profile).toBe('Constrained Baseline')
  expect(track1.Format_Level).toBe('3')
  expect(track1.Format_Settings_CABAC).toBe('No')
  expect(track1.Format_Settings_RefFrames).toBe(3)
  expect(track1.CodecID).toBe('avc1')
  expect(track1.Duration).toBeCloseTo(30.033)
  expect(track1.BitRate).toBeNear(300_000, 2)
  expect(track1.Width).toBe(480)
  expect(track1.Height).toBe(270)
  expect(track1.Stored_Height).toBe(272)
  expect(track1.Sampled_Width).toBe(480)
  expect(track1.PixelAspectRatio).toBeCloseTo(1)
  expect(track1.DisplayAspectRatio).toBeCloseTo(1.778)
  expect(track1.Rotation).toBe('0.000')
  expect(track1.FrameRate_Mode).toBe('CFR')
  expect(track1.FrameRate_Mode_Original).toBe('VFR')
  expect(track1.FrameRate).toBeCloseTo(30)
  expect(track1.FrameCount).toBe(901)
  expect(track1.ColorSpace).toBe('YUV')
  expect(track1.ChromaSubsampling).toBe('4:2:0')
  expect(track1.BitDepth).toBe(8)
  expect(track1.ScanType).toBe('Progressive')
  expect(track1.StreamSize).toBe(1_130_760)
  expect(track1.Encoded_Library).toBe('x264 - core 146 r11M 121396c')
  expect(track1.Encoded_Library_Name).toBe('x264')
  expect(track1.Encoded_Library_Version).toBe('core 146 r11M 121396c')
  expect(track1.Encoded_Library_Settings).toBe(
    'cabac=0 / ref=3 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=48 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=infinite / keyint_min=30 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=300 / ratetol=1.0 / qcomp=0.60 / qpmin=5 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=330 / vbv_bufsize=360 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00'
  )
  if (track1.extra === undefined) {
    throw new Error('Expected extra data on track')
  }
  expect(track1.extra.CodecConfigurationBox).toBe('avcC')

  expectTrackType(track2, 'Audio')
  expect(track2.StreamOrder).toBe('1')
  expect(track2.ID).toBe('2')
  expect(track2.Format).toBe('AAC')
  expect(track2.Format_AdditionalFeatures).toBe('LC')
  expect(track2.CodecID).toBe('mp4a-40-2')
  expect(track2.Duration).toBeCloseTo(30.527)
  expect(track2.BitRate_Mode).toBe('CBR')
  expect(track2.BitRate).toBeNear(112_004, 2)
  expect(track2.Channels).toBe(2)
  expect(track2.ChannelPositions).toBe('Front: L R')
  expect(track2.ChannelLayout).toBe('L R')
  expect(track2.SamplesPerFrame).toBeCloseTo(1024)
  expect(track2.SamplingRate).toBeCloseTo(48_000)
  expect(track2.SamplingCount).toBe(1_465_296)
  expect(track2.FrameRate).toBeCloseTo(46.875)
  expect(track2.FrameCount).toBe(1431)
  expect(track2.Compression_Mode).toBe('Lossy')
  expect(track2.StreamSize).toBe(427_392)
})
